"""Configuration for the sequential graph example."""

from strands.models import BedrockModel

# Model configuration
MODEL_CONFIG = {
    ####"model_id": "us.anthropic.claude-sonnet-4-20250514-v1:0",
    "model_id": "us.anthropic.claude-3-5-sonnet-20241022-v2:0",
    "region_name": "us-east-1"
}

def get_model():
    """Create and return the configured model."""
    return BedrockModel(**MODEL_CONFIG)

# Agent prompts
DATA_CREATION_PROMPT = """
You are a data generation agent for mock transaction data for monthly reports. 
Generate a CSV file in the current directory with 50 rows of mock data for a transaction database for the month specified 
by the user. The file name should be the month of the data.

The data should include the following columns:
- transaction_date
- item_name
- store_name
- transaction_amount
- transaction_category

For file generation use the shell tool.
"""

DATA_ANALYSIS_PROMPT = """
You are a data analysis agent. Analyze the CSV file generated by the data generation agent.
The data file should include the following columns:
- transaction_date
- item_name
- store_name
- transaction_amount
- transaction_category

Take this data and give me a general report with details such as:
- Total number of transactions
- Total amount of transactions
- Average transaction amount
- Total amount of transactions by category
- Top 5 categories by transaction amount
- Top 5 item name by transaction amount
- Top 5 store name by transaction amount
- Top 5 Item name per store based on Transaction amount


Also include any general trends or insights you can find in the data.
Capture the report in a text file in the current directory. The file name should be the month of the data.

For file analysis use the shell tool and look for a CSV file in the current directory. The file name will be the month of the data.
For generating the text file use the shell tool.
""" 